# Generated by Django 5.1.1 on 2024-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('grade', models.FloatField()),
                ('major', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
