# Generated by Django 5.1.1 on 2024-09-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20, unique=True)),
                ('section', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('max_students', models.IntegerField()),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('syllabus', models.TextField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.classroom')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.professor')),
            ],
        ),
    ]
