# Generated by Django 5.1.1 on 2024-09-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_classroom_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '강의실'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '과목'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': '교수'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생'},
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classroom',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='professor',
            table='professor',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
