# Generated by Django 5.1.1 on 2024-10-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_alter_classroom_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '강의실',
                'verbose_name_plural': '강의실들',
                'db_table': 'department',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='example_app.department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
