# Generated by Django 5.1.1 on 2024-10-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_department_remove_course_classroom_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='course_name',
        ),
    ]
